/**
 * boerse-frankfurt.de의 발행자(issuer) 목록은 lang 파라미터를 en으로 바꿔도
 * 국가(주권) 발행자명은 여전히 독일어로만 내려온다(확인됨: lang=en에서도
 * "Brasilien, Föderative Republik" 그대로). 한국 사용자가 영어 국가명으로
 * 검색해도 매칭되도록, 독일어 국가 발행자명(정확히 일치하는 문자열)에 대해
 * 영어 별칭을 하드코딩해두고 검색 시 함께 매칭한다. 회사명은 대부분 이미
 * 영문(라틴)이라 별도 매핑이 필요 없다.
 */
export const COUNTRY_ISSUER_ALIASES: Record<string, string[]> = {
  "Abu Dhabi, Emirate of": ["abu dhabi"],
  "Ägypten, Arabische Republik": ["egypt"],
  "Albanien, Republik": ["albania"],
  "Argentinien, Republik": ["argentina"],
  "Armenien, Republik": ["armenia"],
  "Aserbaidschan, Republik": ["azerbaijan"],
  "Belgien, Königreich": ["belgium"],
  "Bolivien, Republik": ["bolivia"],
  "Brasilien, Föderative Republik": ["brazil"],
  "Bulgarien, Republik": ["bulgaria"],
  "Côte d'Ivoire, Republik": ["ivory coast", "cote d'ivoire"],
  "Dänemark, Königreich": ["denmark"],
  "Deutschland, Bundesrepublik": ["germany"],
  "Dominikanische Republik": ["dominican republic"],
  "Estland, Republik": ["estonia"],
  "Finnland, Republik": ["finland"],
  "Frankreich, Republik": ["france"],
  "Gabunische Republik": ["gabon"],
  "Griechenland, Republik": ["greece"],
  "Großbritannien und Nord-Irland, Vereinigtes Königreich": [
    "united kingdom",
    "great britain",
    "uk",
  ],
  "Indonesien, Republik": ["indonesia"],
  "Irak, Republik": ["iraq"],
  "Irland, Republik": ["ireland"],
  "Island, Republik": ["iceland"],
  "Italien, Republik": ["italy"],
  "Jordanien, Haschemitisches Königreich": ["jordan"],
  "Kamerun, Republik": ["cameroon"],
  "Kasachstan, Republik": ["kazakhstan"],
  "Katar, Staat": ["qatar"],
  "Kenia, Republik": ["kenya"],
  "Kolumbien, Republik": ["colombia"],
  "Kongo, Demokratische Republik": ["congo, democratic republic", "dr congo"],
  "Kongo, Republik": ["congo, republic", "congo-brazzaville"],
  "Korea, Republik": ["korea", "south korea"],
  "Kroatien, Republik": ["croatia"],
  "Lettland, Republik": ["latvia"],
  "Libanon, Republik": ["lebanon"],
  "Litauen, Republik": ["lithuania"],
  "Marokko, Königreich": ["morocco"],
  "Mongolei": ["mongolia"],
  "Georgien": ["georgia"],
  "Neuenburg, Republik und Kanton": ["neuchatel", "neuchâtel"],
  "Niederlande, Königreich der": ["netherlands", "holland"],
  "Nordmazedonien, Republik": ["north macedonia", "macedonia"],
  "Norwegen, Königreich": ["norway"],
  "Österreich, Republik": ["austria"],
  "Philippinen, Republik der": ["philippines"],
  "Polen, Republik": ["poland"],
  "Ruanda, Republik": ["rwanda"],
  "Rumänien, Republik": ["romania"],
  "Sambia, Republik": ["zambia"],
  "Saudi-Arabien, Königreich": ["saudi arabia"],
  "Schweden, Königreich": ["sweden"],
  "Schweizerische Eidgenossenschaft": ["switzerland"],
  "Serbien, Republik": ["serbia"],
  "Singapur, Republik": ["singapore"],
  "Slowakische Republik": ["slovakia"],
  "Slowenien, Republik": ["slovenia"],
  "Spanien, Königreich": ["spain"],
  "Tadschikistan, Republik": ["tajikistan"],
  "Tschechien, Republik": ["czech republic", "czechia"],
  "Türkei, Republik": ["turkey", "turkiye", "türkiye"],
  "Ungarn, Republik": ["hungary"],
  "Usbekistan, Republik": ["uzbekistan"],
  "Vereinigte Mexikanische Staaten": ["mexico"],
  "Zypern, Republik": ["cyprus"],
};
