/**
 * boerse-frankfurt.de의 발행자(issuer) 목록은 lang 파라미터를 en으로 바꿔도
 * 국가(주권) 발행자명은 여전히 독일어로만 내려온다(확인됨: lang=en에서도
 * "Brasilien, Föderative Republik" 그대로). 한국 사용자가 영어 국가명으로
 * 검색해도 매칭되도록, 독일어 국가 발행자명(정확히 일치하는 문자열)에 대해
 * 영어 별칭을 하드코딩해두고 검색 시 함께 매칭한다. 회사명은 대부분 이미
 * 영문(라틴)이라 별도 매핑이 필요 없다.
 */
export const COUNTRY_ISSUER_ALIASES: Record<string, string[]> = {
  "Abu Dhabi, Emirate of": ["abu dhabi"],
  "Ägypten, Arabische Republik": ["egypt"],
  "Albanien, Republik": ["albania"],
  "Argentinien, Republik": ["argentina"],
  "Armenien, Republik": ["armenia"],
  "Aserbaidschan, Republik": ["azerbaijan"],
  "Belgien, Königreich": ["belgium"],
  "Bolivien, Republik": ["bolivia"],
  "Brasilien, Föderative Republik": ["brazil"],
  "Bulgarien, Republik": ["bulgaria"],
  "Côte d'Ivoire, Republik": ["ivory coast", "cote d'ivoire"],
  "Dänemark, Königreich": ["denmark"],
  "Deutschland, Bundesrepublik": ["germany"],
  "Dominikanische Republik": ["dominican republic"],
  "Estland, Republik": ["estonia"],
  "Finnland, Republik": ["finland"],
  "Frankreich, Republik": ["france"],
  "Gabunische Republik": ["gabon"],
  "Griechenland, Republik": ["greece"],
  "Großbritannien und Nord-Irland, Vereinigtes Königreich": [
    "united kingdom",
    "great britain",
    "uk",
  ],
  "Indonesien, Republik": ["indonesia"],
  "Irak, Republik": ["iraq"],
  "Irland, Republik": ["ireland"],
  "Island, Republik": ["iceland"],
  "Italien, Republik": ["italy"],
  "Jordanien, Haschemitisches Königreich": ["jordan"],
  "Kamerun, Republik": ["cameroon"],
  "Kasachstan, Republik": ["kazakhstan"],
  "Katar, Staat": ["qatar"],
  "Kenia, Republik": ["kenya"],
  "Kolumbien, Republik": ["colombia"],
  "Kongo, Demokratische Republik": ["congo, democratic republic", "dr congo"],
  "Kongo, Republik": ["congo, republic", "congo-brazzaville"],
  "Korea, Republik": ["korea", "south korea"],
  "Kroatien, Republik": ["croatia"],
  "Lettland, Republik": ["latvia"],
  "Libanon, Republik": ["lebanon"],
  "Litauen, Republik": ["lithuania"],
  "Marokko, Königreich": ["morocco"],
  "Mongolei": ["mongolia"],
  "Georgien": ["georgia"],
  "Neuenburg, Republik und Kanton": ["neuchatel", "neuchâtel"],
  "Niederlande, Königreich der": ["netherlands", "holland"],
  "Nordmazedonien, Republik": ["north macedonia", "macedonia"],
  "Norwegen, Königreich": ["norway"],
  "Österreich, Republik": ["austria"],
  "Philippinen, Republik der": ["philippines"],
  "Polen, Republik": ["poland"],
  "Ruanda, Republik": ["rwanda"],
  "Rumänien, Republik": ["romania"],
  "Sambia, Republik": ["zambia"],
  "Saudi-Arabien, Königreich": ["saudi arabia"],
  "Schweden, Königreich": ["sweden"],
  "Schweizerische Eidgenossenschaft": ["switzerland"],
  "Serbien, Republik": ["serbia"],
  "Singapur, Republik": ["singapore"],
  "Slowakische Republik": ["slovakia"],
  "Slowenien, Republik": ["slovenia"],
  "Spanien, Königreich": ["spain"],
  "Tadschikistan, Republik": ["tajikistan"],
  "Tschechien, Republik": ["czech republic", "czechia"],
  "Türkei, Republik": ["turkey", "turkiye", "türkiye"],
  "Ungarn, Republik": ["hungary"],
  "United States of America": ["us", "usa"],
  "Usbekistan, Republik": ["uzbekistan"],
  "Vereinigte Mexikanische Staaten": ["mexico"],
  "Zypern, Republik": ["cyprus"],
};

/**
 * 종목검색에서 발행자가 국가(주권) 자체인 경우(=국채), tradingeconomics.com의
 * 국가 슬러그(country-list/rating 페이지의 href="/{slug}/rating")로 연결해
 * 신용등급을 자동 반영하는 데 쓴다. 한국채권검색의 국고채권, 미국채권검색의
 * U.S. Treasury와 동일한 취급이다. 슬러그는 tradingeconomics.com 실제 링크를
 * 확인해 매핑했다(예: "Nordmazedonien, Republik" -> 실제 슬러그는
 * "north-macedonia"가 아니라 "macedonia").
 */
export const COUNTRY_ISSUER_SLUGS: Record<string, string> = {
  "Ägypten, Arabische Republik": "egypt",
  "Albanien, Republik": "albania",
  "Angola, Republik": "angola",
  "Argentinien, Republik": "argentina",
  "Armenien, Republik": "armenia",
  "Aserbaidschan, Republik": "azerbaijan",
  "Bahrain, Königreich": "bahrain",
  "Belgien, Königreich": "belgium",
  "Benin, Republik": "benin",
  "Bolivien, Republik": "bolivia",
  "Brasilien, Föderative Republik": "brazil",
  "Bulgarien, Republik": "bulgaria",
  "Chile, Republik": "chile",
  "Costa Rica, Republik": "costa-rica",
  "Côte d'Ivoire, Republik": "ivory-coast",
  "Dänemark, Königreich": "denmark",
  "Deutschland, Bundesrepublik": "germany",
  "Dominikanische Republik": "dominican-republic",
  "Ecuador, Republik": "ecuador",
  "El Salvador, Republik": "el-salvador",
  "Estland, Republik": "estonia",
  "Finnland, Republik": "finland",
  "Frankreich, Republik": "france",
  "Gabunische Republik": "gabon",
  "Ghana, Republic of": "ghana",
  "Griechenland, Republik": "greece",
  "Großbritannien und Nord-Irland, Vereinigtes Königreich": "united-kingdom",
  "Guatemala, Republik": "guatemala",
  "Honduras, Republik": "honduras",
  "Indonesien, Republik": "indonesia",
  "Irak, Republik": "iraq",
  "Irland, Republik": "ireland",
  "Island, Republik": "iceland",
  "Israel, Staat": "israel",
  "Italien, Republik": "italy",
  "Jordanien, Haschemitisches Königreich": "jordan",
  "Kamerun, Republik": "cameroon",
  "Kasachstan, Republik": "kazakhstan",
  "Katar, Staat": "qatar",
  "Kenia, Republik": "kenya",
  "Kolumbien, Republik": "colombia",
  "Korea, Republik": "south-korea",
  "Kroatien, Republik": "croatia",
  "Lettland, Republik": "latvia",
  "Libanon, Republik": "lebanon",
  "Litauen, Republik": "lithuania",
  "Malta, Republik": "malta",
  "Marokko, Königreich": "morocco",
  "Mongolei": "mongolia",
  "Georgien": "georgia",
  "Montenegro, Republik": "montenegro",
  "Niederlande, Königreich der": "netherlands",
  "Nigeria, Bundesrepublik": "nigeria",
  "Nordmazedonien, Republik": "macedonia",
  "Norwegen, Königreich": "norway",
  "Oman, Sultanat": "oman",
  "Österreich, Republik": "austria",
  "Pakistan, Islamische Republik": "pakistan",
  "Panama, Republik": "panama",
  "Paraguay, Republik": "paraguay",
  "Peru, Republik": "peru",
  "Philippinen, Republik der": "philippines",
  "Polen, Republik": "poland",
  "Portugal, Republik": "portugal",
  "Ruanda, Republik": "rwanda",
  "Rumänien, Republik": "romania",
  "Sambia, Republik": "zambia",
  "San Marino, Republik": "san-marino",
  "Saudi-Arabien, Königreich": "saudi-arabia",
  "Schweden, Königreich": "sweden",
  "Schweizerische Eidgenossenschaft": "switzerland",
  "Senegal, Republik": "senegal",
  "Serbien, Republik": "serbia",
  "Singapur, Republik": "singapore",
  "Slowakische Republik": "slovakia",
  "Slowenien, Republik": "slovenia",
  "Spanien, Königreich": "spain",
  "Sri Lanka, Demokratische Sozialistische Republik": "sri-lanka",
  "State of Kuwait": "kuwait",
  "Suriname, Republik": "suriname",
  "Tadschikistan, Republik": "tajikistan",
  "Trinidad & Tobago, Republik": "trinidad-and-tobago",
  "Tschechien, Republik": "czech-republic",
  "Türkei, Republik": "turkey",
  "Ungarn, Republik": "hungary",
  "United Arab Emirates, Federal Government of": "united-arab-emirates",
  "United States of America": "united-states",
  "Ukraine, Republik": "ukraine",
  "Uruguay, Republik": "uruguay",
  "Usbekistan, Republik": "uzbekistan",
  "Venezuela, Bolivarische Republik": "venezuela",
  "Vereinigte Mexikanische Staaten": "mexico",
  "Zypern, Republik": "cyprus",
};
